os:         linux
language:   python

python:
    - 2.7
    - 3.6

env:
    matrix:
        - TF_PREBUILT_VERSION=1.5.0

matrix:
    include:
        - os: osx
          language: generic
          python:   2.7
          env:      WANTED_PYTHON_VERSION=2.7 TF_PREBUILT_VERSION=1.5.0
        - os: osx
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6 TF_PREBUILT_VERSION=1.5.0

before_install:
    - |
        if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew update                                                         # this swaps python versions and makes 3 the default one

            if [ "$WANTED_PYTHON_VERSION" == "2.7" ]; then
                brew reinstall python\@2 || brew link --overwrite python\@2     # install and link python2 and pip2 to /usr/local/bin
            else
                brew reinstall python                                           # install and link python3 and pip3 to /usr/local/bin
            fi
            export PATH=/usr/local/opt/python/libexec/bin:$PATH

            export CK_PLATFORM_INDEX=2                                          # used later by CK
        else
            sudo apt-get update -qq
            sudo apt-get install python-pip
            export WANTED_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION                 # since Python is supported in Linux, get it from Travis
            export CK_PLATFORM_INDEX=1                                          # used later by CK
        fi

install:
    - CWD=`pwd`
    - REPO_NAME=`basename $CWD`
    - echo "os=${TRAVIS_OS_NAME}, python=${WANTED_PYTHON_VERSION}, TF_prebuilt_version=${TF_PREBUILT_VERSION}"
    - which python
    - python --version
    - python -m pip install --ignore-installed --verbose pip setuptools                         # make sure pip is also up to date no matter what
    - python -m pip install ck                                                                  # CK kernel itself
    - ck pull repo:${REPO_NAME}                                                                 # ...also trigger pulling dependent repositories
    - echo $CK_PLATFORM_INDEX | ck detect platform.os --update_platform_init                    # set the platform to generic-linux (1) or generic-macos (2)
    -       ck detect soft:compiler.python --full_path=`which python`                           # pick the one Travis has set for us in the PATH
    -       ck install package --tags=lib,tensorflow,v${TF_PREBUILT_VERSION},vcpu,vprebuilt     # install prebuilt tensorflow package
    -       ck install package:lib-keras-2.1.3-request                                          # install prebuilt keras package

script:
    - ck run program:request-iot-benchmark --cmd_key=benchmark-alexnet-single-device-cpu        # AlexNet benchmark
    - ck run program:request-iot-benchmark --cmd_key=benchmark-vgg16-single-device-cpu          # VGG16 benchmark

